{"uuid": "1ec813ed-210b-4e0f-a374-c5d53c3bb01d", "children": ["8253fcb0-0118-4326-a473-3b82d4734410"], "befores": [{"name": "set_browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021B533E0090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "trace": "  File \"C:\\Users\\asya4\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\PycharmProjects\\qa_guru_python_1_9_jenkins\\tests\\conftest.py\", line 45, in set_browser\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 428, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 347, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 369, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\urllib3\\request.py\", line 81, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\urllib3\\request.py\", line 173, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 827, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 827, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 827, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 799, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\asya4\\venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1699029176992, "stop": 1699029187849}], "start": 1699029176992, "stop": 1699029188718}